import { useMemo, useState } from "react";
import reportsData from "./reportsData.json";

const statusClasses: Record<string, string> = {
  Success: "bg-emerald-100 text-emerald-800 border-emerald-300",
  Delayed: "bg-amber-100 text-amber-800 border-amber-300",
  Failed: "bg-rose-100 text-rose-800 border-rose-300"
};

const priorityClasses: Record<string, string> = {
  High: "bg-rose-100 text-rose-700",
  Medium: "bg-amber-100 text-amber-700",
  Low: "bg-emerald-100 text-emerald-700"
};

export default function ReportsPage() {
  const [selectedCategory, setSelectedCategory] = useState("all");
  const [viewMode, setViewMode] = useState("grid");

  const {
    reportsSummary,
    reportCategories,
    reportCatalog,
    upcomingSchedules,
    departmentConsumption,
    monthlyTrend,
    alerts
  } = reportsData;

  const filteredReports = useMemo(() => {
    if (selectedCategory === "all") {
      return reportCatalog;
    }
    return reportCatalog.filter((report) => report.category === selectedCategory);
  }, [reportCatalog, selectedCategory]);

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50/30 to-indigo-50/50 p-8">
      <div className="max-w-[1800px] mx-auto space-y-8">
        <div className="relative overflow-hidden rounded-3xl bg-gradient-to-r from-blue-600 via-indigo-600 to-cyan-600 p-10 shadow-2xl">
          <div className="absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjAiIGhlaWdodD0iNjAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2Zz48ZGVmcz48cGF0dGVybiBpZD0iZ3JpZCIgd2lkdGg9IjYwIiBoZWlnaHQ9IjYwIiBwYXR0ZXJuVW5pdHM9InVzZXJTcGFjZU9uVXNlIj48cGF0aCBkPSJNIDEwIDAgTCAwIDAgMCAxMCIgZmlsbD0ibm9uZSIgc3Ryb2tlPSJ3aGl0ZSIgc3Ryb2tlLW9wYWNpdHk9IjAuMSIgc3Ryb2tlLXdpZHRoPSIxIi8+PC9wYXR0ZXJuPjwvZGVmcz48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSJ1cmwoI2dyaWQpIi8+PC9zdmc+')] opacity-30"></div>
          <div className="relative flex flex-col md:flex-row md:items-center md:justify-between gap-6">
            <div>
              <div className="flex items-center gap-4 mb-3">
                <div className="w-16 h-16 rounded-2xl bg-white/20 backdrop-blur-sm flex items-center justify-center text-4xl">
                  📄
                </div>
                <div>
                  <h1 className="text-5xl font-black text-white tracking-tight">Reports</h1>
                  <p className="text-blue-100 text-lg mt-1 font-medium">Analytics, exports and scheduled insights</p>
                </div>
              </div>
              <div className="flex flex-wrap gap-3 mt-4">
                <div className="px-5 py-2 rounded-full bg-white/20 backdrop-blur-sm text-white text-sm font-semibold border border-white/30">
                  📊 {reportsSummary.totalReports} Total Reports
                </div>
                <div className="px-5 py-2 rounded-full bg-white/20 backdrop-blur-sm text-white text-sm font-semibold border border-white/30">
                  ⚡ {reportsSummary.autoGenerated} Auto Generated
                </div>
                <div className="px-5 py-2 rounded-full bg-white/20 backdrop-blur-sm text-white text-sm font-semibold border border-white/30">
                  📅 {reportsSummary.scheduledToday} Scheduled Today
                </div>
              </div>
            </div>

            <div className="flex flex-wrap gap-3">
              <button className="px-8 py-4 bg-white text-blue-600 rounded-xl font-bold hover:shadow-lg transition-all hover:scale-105 text-lg">
                ➕ Create Report
              </button>
              <button className="px-6 py-4 bg-white/20 backdrop-blur-sm text-white border border-white/30 rounded-xl font-bold hover:bg-white/30 transition-all">
                🗂️ Export Center
              </button>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-8 gap-5">
          {[
            { label: "Total Reports", value: reportsSummary.totalReports, icon: "📄", color: "from-blue-500 to-blue-600" },
            { label: "Auto Reports", value: reportsSummary.autoGenerated, icon: "🤖", color: "from-indigo-500 to-indigo-600" },
            { label: "Scheduled Today", value: reportsSummary.scheduledToday, icon: "📅", color: "from-cyan-500 to-cyan-600" },
            { label: "Failed Runs", value: reportsSummary.failedReports, icon: "⚠️", color: "from-rose-500 to-rose-600" },
            { label: "Avg Gen Time", value: `${reportsSummary.avgGenerationTimeSec}s`, icon: "⏱️", color: "from-amber-500 to-amber-600" },
            { label: "Storage Used", value: `${reportsSummary.storageUsedGb} GB`, icon: "🗃️", color: "from-purple-500 to-purple-600" },
            { label: "Monthly Exports", value: reportsSummary.exportRequestsThisMonth, icon: "📤", color: "from-emerald-500 to-emerald-600" },
            { label: "Data Freshness", value: `${reportsSummary.dataFreshnessMins} min`, icon: "🔄", color: "from-teal-500 to-teal-600" }
          ].map((metric, idx) => (
            <div key={idx} className="group relative bg-white rounded-2xl p-5 shadow-lg hover:shadow-2xl transition-all duration-300 border border-gray-100 hover:border-gray-200 hover:-translate-y-1">
              <div className={`absolute top-0 left-0 w-full h-1.5 bg-gradient-to-r ${metric.color} rounded-t-2xl`}></div>
              <div className="text-3xl mb-2">{metric.icon}</div>
              <div className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">{metric.label}</div>
              <div className="text-2xl font-black text-gray-900">{metric.value}</div>
            </div>
          ))}
        </div>

        <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
          <div className="flex flex-wrap gap-2 bg-white rounded-2xl p-2 shadow-lg border border-gray-200">
            {reportCategories.map((category) => (
              <button
                key={category.id}
                onClick={() => setSelectedCategory(category.id)}
                className={`px-4 py-2 rounded-lg font-bold text-sm transition-all ${
                  selectedCategory === category.id
                    ? "bg-blue-500 text-white"
                    : "text-gray-600 hover:bg-gray-100"
                }`}
              >
                {category.label}
              </button>
            ))}
          </div>

          <div className="flex gap-2 bg-white rounded-2xl p-2 shadow-lg border border-gray-200">
            <button
              onClick={() => setViewMode("grid")}
              className={`px-4 py-2 rounded-lg font-bold transition-all ${
                viewMode === "grid"
                  ? "bg-indigo-500 text-white"
                  : "text-gray-600 hover:bg-gray-100"
              }`}
            >
              📊 Grid
            </button>
            <button
              onClick={() => setViewMode("table")}
              className={`px-4 py-2 rounded-lg font-bold transition-all ${
                viewMode === "table"
                  ? "bg-indigo-500 text-white"
                  : "text-gray-600 hover:bg-gray-100"
              }`}
            >
              📋 Table
            </button>
          </div>
        </div>

        {viewMode === "grid" ? (
          <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
            {filteredReports.map((report) => (
              <div key={report.id} className="bg-white rounded-2xl p-6 shadow-lg hover:shadow-2xl transition-all border border-gray-100 hover:border-blue-300 hover:-translate-y-1">
                <div className="flex items-center justify-between mb-4">
                  <div className="text-xs font-bold text-gray-500 uppercase">{report.id}</div>
                  <span className={`px-3 py-1 rounded-full text-xs font-bold border ${statusClasses[report.status] || "bg-gray-100 text-gray-800 border-gray-300"}`}>
                    {report.status}
                  </span>
                </div>

                <h3 className="text-2xl font-black text-gray-900 mb-2">{report.name}</h3>
                <p className="text-sm text-gray-600 font-semibold mb-4">
                  {report.owner} • {report.frequency} • {report.format}
                </p>

                <div className="space-y-3">
                  <div className="flex items-center justify-between text-sm">
                    <span className="text-gray-600 font-semibold">Last Run</span>
                    <span className="font-bold text-gray-900">{report.lastRun}</span>
                  </div>
                  <div className="flex items-center justify-between text-sm">
                    <span className="text-gray-600 font-semibold">Records</span>
                    <span className="font-bold text-gray-900">{report.records}</span>
                  </div>
                  <div className="flex items-center justify-between text-sm">
                    <span className="text-gray-600 font-semibold">SLA</span>
                    <span className="font-bold text-indigo-700">{report.slaMins} mins</span>
                  </div>
                </div>

                <div className="mt-5 flex gap-2">
                  <button className="flex-1 rounded-xl bg-gradient-to-r from-blue-500 to-indigo-600 px-4 py-2 text-sm font-bold text-white hover:shadow-lg transition-all">
                    Generate
                  </button>
                  <button className="flex-1 rounded-xl border border-gray-300 px-4 py-2 text-sm font-bold text-gray-700 hover:bg-gray-100 transition-colors">
                    Preview
                  </button>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div className="bg-white rounded-3xl p-8 shadow-xl border border-gray-100">
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="bg-gray-50 border-b-2 border-gray-200">
                    <th className="px-4 py-4 text-left text-xs font-bold text-gray-600 uppercase">Report</th>
                    <th className="px-4 py-4 text-left text-xs font-bold text-gray-600 uppercase">Owner</th>
                    <th className="px-4 py-4 text-left text-xs font-bold text-gray-600 uppercase">Frequency</th>
                    <th className="px-4 py-4 text-right text-xs font-bold text-gray-600 uppercase">Records</th>
                    <th className="px-4 py-4 text-left text-xs font-bold text-gray-600 uppercase">Last Run</th>
                    <th className="px-4 py-4 text-center text-xs font-bold text-gray-600 uppercase">Status</th>
                  </tr>
                </thead>
                <tbody>
                  {filteredReports.map((report) => (
                    <tr key={report.id} className="border-b border-gray-200 hover:bg-gray-50 transition-colors">
                      <td className="px-4 py-4">
                        <div className="font-bold text-gray-900">{report.name}</div>
                        <div className="text-xs text-gray-600">{report.id} • {report.format}</div>
                      </td>
                      <td className="px-4 py-4 text-gray-800 font-semibold">{report.owner}</td>
                      <td className="px-4 py-4 text-gray-800 font-semibold">{report.frequency}</td>
                      <td className="px-4 py-4 text-right font-bold text-gray-900">{report.records}</td>
                      <td className="px-4 py-4 text-gray-800 font-semibold">{report.lastRun}</td>
                      <td className="px-4 py-4 text-center">
                        <span className={`px-3 py-1 rounded-full text-xs font-bold border ${statusClasses[report.status] || "bg-gray-100 text-gray-800 border-gray-300"}`}>
                          {report.status}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        <div className="grid grid-cols-1 xl:grid-cols-2 gap-8">
          <div className="bg-white rounded-3xl p-8 shadow-xl border border-gray-100">
            <div className="flex items-center gap-3 mb-8">
              <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center text-2xl">
                ⏰
              </div>
              <div>
                <h2 className="text-3xl font-black text-gray-900">Schedule Queue</h2>
                <p className="text-gray-600 text-sm mt-0.5">Upcoming automated reports</p>
              </div>
            </div>
            <div className="space-y-4">
              {upcomingSchedules.map((item, idx) => (
                <div key={idx} className="rounded-2xl border border-gray-200 bg-gray-50 p-5">
                  <div className="flex items-center justify-between gap-3">
                    <div>
                      <div className="text-lg font-bold text-gray-900">{item.name}</div>
                      <div className="text-sm text-gray-600">{item.audience}</div>
                    </div>
                    <div className="text-right">
                      <div className="text-sm font-black text-indigo-700">{item.nextRun}</div>
                      <span className={`inline-block mt-1 rounded-full px-3 py-1 text-xs font-bold ${priorityClasses[item.priority] || "bg-gray-100 text-gray-700"}`}>
                        {item.priority}
                      </span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="bg-white rounded-3xl p-8 shadow-xl border border-gray-100">
            <div className="flex items-center gap-3 mb-8">
              <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center text-2xl">
                📈
              </div>
              <div>
                <h2 className="text-3xl font-black text-gray-900">Consumption Trend</h2>
                <p className="text-gray-600 text-sm mt-0.5">Department and monthly usage</p>
              </div>
            </div>

            <div className="space-y-4 mb-7">
              {departmentConsumption.map((item) => (
                <div key={item.department}>
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-sm font-bold text-gray-800">{item.department}</span>
                    <span className="text-sm font-bold text-gray-700">{item.requests} requests ({item.share}%)</span>
                  </div>
                  <div className="h-2.5 bg-gray-200 rounded-full overflow-hidden">
                    <div
                      className="h-full bg-gradient-to-r from-emerald-400 to-teal-600 rounded-full"
                      style={{ width: `${item.share}%` }}
                    ></div>
                  </div>
                </div>
              ))}
            </div>

            <div className="grid grid-cols-5 gap-3">
              {monthlyTrend.map((item) => (
                <div key={item.month} className="rounded-xl border border-gray-200 bg-gray-50 p-3 text-center">
                  <div className="text-xs font-bold text-gray-600">{item.month}</div>
                  <div className="text-lg font-black text-gray-900">{item.generated}</div>
                  <div className="text-xs font-semibold text-rose-700">Fail: {item.failed}</div>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="bg-gradient-to-r from-rose-50 to-orange-50 border-l-4 border-rose-500 rounded-2xl p-6">
          <div className="font-black text-rose-900 mb-4 text-lg flex items-center gap-2">
            <span>🚨</span> Reporting Alerts
          </div>
          <div className="space-y-3">
            {alerts.map((alert, idx) => (
              <div key={idx} className="bg-white/60 rounded-xl border border-rose-200 p-4 text-sm font-medium text-rose-800">
                {alert}
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
